openapi: 3.0.0
info:
  title: claims
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas:
    ClaimRequest:
      title: ClaimRequest
      type: object
      description: Its a ClaimRequest data model and it contains Claim information
      properties:
        claimId:
          type: number
           type:
                  type: string
                status:
                  type: string
                policyId:
                  type: string
                ClaimInfo:
                  title: ClaimInfo
                  type: object
                  description: Claim info data model contains claim info
                  properties:
                    id:
                      type: number
                    'submissionDate:':
                      type: string
                      format: date
                      pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
                    gender:
                      type: string
                      enum:
                        - FEMALE
                        - MALE
                        - UNKNOWN
                    dob:
                      type: string
                      pattern: '[\d]{4}-[0-1][0-9]-[0-3][0-9]'
                      format: date
                    email:
                      type: string
                      format: email
                      pattern: '([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})'
                  required:
                    - id
              required:
                - claimId              
    ClaimInfo:
      title: ClaimInfo.v1
      type: object
      description: Claim info data model contains claim info
      properties:
        id:
          type: number
        'submissionDate:':
          type: string
          format: date
          pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
        gender:
          type: string
          enum:
            - FEMALE
            - MALE
            - UNKNOWN
        dob:
          type: string
          pattern: '[\d]{4}-[0-1][0-9]-[0-3][0-9]'
          format: date
        email:
          type: string
          format: email
          pattern: '([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})'
      required:
        - id



    
