openapi: 3.0.0
info:
  title: common
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas:
    Error:
      title: Error
      type: object
      description: It contains error info
      properties:
        id:
          type: string
        erroCode:
          type: string
        errorMessage:
          type: string


