openapi: 3.0.0
info:
  title: Demo
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /api:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../Claims/ClaimRequest.v1.yaml
      operationId: get-api
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
components:
  schemas: {}
