openapi: 3.0.0
info:
  title: getClaim
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /getClaims:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./Policies.v1.yaml#/components/schemas/PolicyDetails
      operationId: get-getClaims
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../Members/Address.v1.yaml
components:
  schemas: {}
