openapi: '3.0.0'
info:
  title: Test2
  version: '1.0'
servers:
- url: http://localhost:3000
paths: {}
components:
  schemas: 
    title: PolicyDetails
type: object
x-examples:
  PolicyDetails:
    policyId: 1
    policyName: Health
    Product:
      productId: 1
      productName: Credit Card
      productDescription: This is for credit card
    Preference:
      id: '123'
      details: Its user preference
    Address:
      addressId: 0
      address1: Electronic
      street: city
      city: Bangalore
      state: Karnataka
      country: India
      zip: '560000'
      Contact:
        mobile: 9999999999
        emailId: Messi@gmail.com
        phoneNumber: 9999999999
  PolicyDetails schema:
    policyId: 0
    policyName: string
    Product:
      productId: 0
      productName: string
      productDescription: string
    Preference:
      id: string
      details: string
    Address:
      addressId: 0
      address1: string
      street: string
      city: string
      state: string
      country: string
      zip: string
      Contact:
        mobile: 9999999999
        emailId: string
        phoneNumber: 0
  example-3:
    policyId: 0
    policyName: string
    Product:
      productId: 0
      productName: string
      productDescription: string
    Preference:
      id: string
      details: string
    Address:
      addressId: 0
      address1: string
      street: string
      city: string
      state: string
      country: string
      zip: string
      Contact:
        mobile: 9999999999
        emailId: string
    Contact:
      mobile: 9999999999
      emailId: string
description: Its a PolicyDetails data model contains Policy details
properties:
  policyId:
    type: number
  policyName:
    type: string
  Product:
    $ref: ./Product/Product.v1.yaml
  Preference:
    $ref: ../Members/Preference.v1.yaml
  Address:
    $ref: ../Members/Address.v1.yaml
  Contact:
    $ref: ../Members/Contact.v1.yaml
required:
  - policyId

